### ISSUE TITLE
couldnt open the events in contact us page

### ISSUE THREAD

**Issue by lokeshwartabjula** [lokeshwartabjula/Incognito2k17#10]
i hope there is a javascript (onclick() function) problem while clicking on the diamonds

**Comment by syedjafer** [comment]
![screenshot from 2017-08-25 21-32-07](https://user-images.githubusercontent.com/20949510/29722030-ea96ec1a-89dc-11e7-8f5b-350f420fe8d2.png

**Comment by syedjafer** [comment]
FINISHED
