### ISSUE TITLE
highlight the current page in white in top nav-bar 

### ISSUE THREAD

**Issue by garrykevin-ep** [lokeshwartabjula/Incognito2k17#4]

**Comment by garrykevin-ep** [comment]
home is highlighted in all pages

**Comment by syedjafer** [comment]
in title ?

**Comment by garrykevin-ep** [comment]
in nav bar

**Comment by garrykevin-ep** [comment]
![screen shot 2017-08-25 at 12 58 24 pm](https://user-images.githubusercontent.com/21335581/29703944-5e624736-8995-11e7-83e4-110e2951c46e.png)
highlight the current page in white not home

**Comment by syedjafer** [comment]
I tried 
`ul#menu1 li:active{
  color:white;
}

ul#menu2 li:active{
  color:white;
}

ul#menu1 li:visited{
  color:white;
}`
But when we click on some element the page refreshes .so it automatically make HOME button to turn to white.

**Comment by garrykevin-ep** [comment]
just add remove white color from home 
and add to the current page

**Comment by garrykevin-ep** [comment]
![screen shot 2017-08-25 at 3 45 33 pm](https://user-images.githubusercontent.com/21335581/29710110-9dbb0d34-89ac-11e7-8779-370e8b68a571.png)
change this to
![screen shot 2017-08-25 at 3 46 17 pm](https://user-images.githubusercontent.com/21335581/29710122-ab4f9bae-89ac-11e7-9ddc-5571a9954638.png)

**Comment by syedjafer** [comment]
But if we have more pages , its difficult to follow this

**Comment by garrykevin-ep** [comment]
why?we should for all pages
not a difficult task

**Comment by syedjafer** [comment]
I thought of reducing the coding time:
 I also tried with jquery 
```javascript

$('ul#menu1 a').click(function(){
      $(this).css('color', 'white');
});
```

Ok but for now i finish it with ur idea.

**Comment by garrykevin-ep** [comment]
that jquery wont work
it will change the color when only when it is clicked
but when u click it will take u to the next page:facepunch:

**Comment by syedjafer** [comment]
Ohhhh . Anyway that is been fixed .
