### ISSUE TITLE
upload images for contact us html

### ISSUE THREAD

**Issue by lokeshwartabjula** [lokeshwartabjula/Incognito2k17#9]
upload all the following images in this directory

 img/2018/fields/
![robowars](https://user-images.githubusercontent.com/31277771/29718417-61396ac6-89d0-11e7-88ba-e75576c31c6f.jpg)
![oc](https://user-images.githubusercontent.com/31277771/29718418-61395504-89d0-11e7-9213-c43f7ecf6c33.jpg)
![money](https://user-images.githubusercontent.com/31277771/29718419-6139f5d6-89d0-11e7-949d-bf900c36aabd.jpg)
![marketing](https://user-images.githubusercontent.com/31277771/29718422-6142aed8-89d0-11e7-8bb3-aca7681434d7.jpg)
![ideate-1](https://user-images.githubusercontent.com/31277771/29718421-614112a8-89d0-11e7-8332-dad5b8725149.jpg)
![fnb nd hospi](https://user-images.githubusercontent.com/31277771/29718420-613feb80-89d0-11e7-92ba-1f558855e9b7.jpg)
![exhi](https://user-images.githubusercontent.com/31277771/29718423-61784156-89d0-11e7-8cb2-0c5e15a94389.jpg)

**Comment by syedjafer** [comment]
Yeah Dude
